function tests = test_subsample_grid_2d

tests = functiontests(localfunctions);

end


function test_1(testCase)
% Test function on 2x2x2 grid expanded by factor of 2.

inc = 2;
f_orig(:, :, 1) = [ ...
    [1, 1, 2, 2]; ...
    [1, 1, 2, 2]; ...
    [3, 3, 4, 4]; ...
    [3, 3, 4, 4]; ...
];
f_orig(:, :, 2) = [ ...
    [1, 1, 2, 2]; ...
    [1, 1, 2, 2]; ...
    [3, 3, 4, 4]; ...
    [3, 3, 4, 4]; ...
];
f_orig(:, :, 3) = [ ...
    [5, 5, 6, 6]; ...
    [5, 5, 6, 6]; ...
    [7, 7, 8, 8]; ...
    [7, 7, 8, 8]; ...
];
f_orig(:, :, 4) = [ ...
    [5, 5, 6, 6]; ...
    [5, 5, 6, 6]; ...
    [7, 7, 8, 8]; ...
    [7, 7, 8, 8]; ...
];

f_subsmp(:, :, 1) = [ ...
    [1, 2]; ...
    [3, 4] ...
];
f_subsmp(:, :, 2) = [ ...
    [5, 6]; ...
    [7, 8] ...
];

result = subsample_grid_3d(f_orig, inc);
verifyEqual(testCase, result, f_subsmp);

end


function test_2(testCase)
% Test that subsampling expanded grid returns original grid.

inc = 2;
f_orig(:, :, 1) = [ ...
    [1, 2]; ...
    [3, 4] ...
];
f_orig(:, :, 2) = [ ...
    [5, 6]; ...
    [7, 8] ...
];

result = subsample_grid_3d(expand_grid_3d(f_orig, inc), inc);
verifyEqual(testCase, result, f_orig);

end


