function tests = test_expand_grid_2d

tests = functiontests(localfunctions);

end


function test_1(testCase)
% Test function on 2x2 grid expanded by factor of 2.

inc = 2;
f_orig = [ ...
    [1, 2]; ...
    [3, 4] ...
];
f_exp = [ ...
    [1, 1, 2, 2]; ...
    [1, 1, 2, 2]; ...
    [3, 3, 4, 4]; ...
    [3, 3, 4, 4]; ...
];

result = expand_grid_2d(f_orig, inc);
verifyEqual(testCase, result, f_exp);

end


function test_2(testCase)
% Test function on 3x2 grid expanded by factor of 2.

inc = 2;
f_orig = [ ...
    [1, 2]; ...
    [3, 4]; ...
    [5, 6] ...
];
f_exp = [ ...
    [1, 1, 2, 2]; ...
    [1, 1, 2, 2]; ...
    [3, 3, 4, 4]; ...
    [3, 3, 4, 4]; ...
    [5, 5, 6, 6]; ...
    [5, 5, 6, 6] ...
];

result = expand_grid_2d(f_orig, inc);
verifyEqual(testCase, result, f_exp);

end


function test_3(testCase)
% Test function on 2x2 grid expanded by factor of 3.

inc = 3;
f_orig = [ ...
    [1, 2]; ...
    [3, 4] ...
];
f_exp = [ ...
    [1, 1, 1, 2, 2, 2]; ...
    [1, 1, 1, 2, 2, 2]; ...
    [1, 1, 1, 2, 2, 2]; ...
    [3, 3, 3, 4, 4, 4]; ...
    [3, 3, 3, 4, 4, 4]; ...
    [3, 3, 3, 4, 4, 4] ...
];

result = expand_grid_2d(f_orig, inc);
verifyEqual(testCase, result, f_exp);

end
